[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  set background=dark
  augroup colorschemeSetting
    autocmd!
    autocmd VimEnter * ++nested colorscheme iceberg
  augroup END
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
set laststatus=2
" https://github.com/itchyny/lightline.vim#introduction
if !has('gui_running')
  set t_Co=256
endif
let g:lightline = {
      \ 'colorscheme': 'iceberg',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'cocstatus', 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'cocstatus': 'coc#status',
      \   'gitbranch': 'fugitive#head'
      \ },
      \ }
'''

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'let g:rainbow_active = 1'

[[plugins]]
repo = 'mileszs/ack.vim'
if = '''executable('ag')'''
hook_add = '''
if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
if = '''executable('node')'''
merged = '0'
hook_add = '''
nmap <Leader>c [coc.nvim]
nnoremap [coc.nvim] <Nop>

" Remap keys for gotos
nmap <silent> [coc.nvim]d <Plug>(coc-definition)
nmap <silent> [coc.nvim]y <Plug>(coc-type-definition)
nmap <silent> [coc.nvim]i <Plug>(coc-implementation)
nmap <silent> [coc.nvim]r <Plug>(coc-references)

" Show documentation in preview window
nnoremap <silent> [coc.nvim]K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Remap for rename current word
nmap [coc.nvim]rn <Plug>(coc-rename)

" Use `:Format` to format current buffer
command! -nargs=0 Format :call CocAction('format')
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'qpkorr/vim-renamer'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nmap <Leader>n [nerdtree]
nnoremap [nerdtree] <Nop>
nnoremap [nerdtree]t :NERDTreeToggle<Enter>
nnoremap <silent> [nerdtree]f :NERDTreeFind<Enter>
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

#[[plugins]]
#repo = 'w0rp/ale'
#hook_add = '''
#let g:ale_linters = {
#\  'php': ['phpcs'],
#\}
#let g:ale_php_phpcs_standard = 'PSR2'
#let g:ale_fixers = {}
#let g:ale_fixers['php'] = ['php_cs_fixer']
#'''
