tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "kryptco/tap"
tap "universal-ctags/universal-ctags"
brew "ansible"
brew "bash-completion"
brew "composer"
brew "fzf"
brew "git"
brew "jq"
brew "mas"
brew "node"
brew "packer"
brew "php"
brew "starship"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "yarn"
brew "kryptco/tap/kr"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "docker"
cask "font-source-code-pro-for-powerline"
cask "google-chrome"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
mas "Evernote", id: 406056744
mas "GIPHY CAPTURE", id: 668208984
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "LastPass", id: 926036361
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
